name: CI-dev

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ dev ]
    paths:
      - '**.py'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: development

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use debug config
        run: mv -f $GITHUB_WORKSPACE/config_dev.py $GITHUB_WORKSPACE/config.py

      - name: Insert bot telegram token
        uses: jwsi/secret-parser@v1
        with:
          filename: config.py
          secret-name: bot_token
          secret-value: ${{ secrets.BOT_TOKEN }}
      
      - name: Insert developer id
        uses: jwsi/secret-parser@v1
        with:
          filename: config.py
          secret-name: developer_id
          secret-value: ${{ secrets.DEVELOPER_ID }}
      
      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@5.1
        with:
          switches: -avzr --delete --exclude='.git' --exclude='stats.json'
          remote_path: ${{ secrets.DEPLOY_PATH }}
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_port: ${{ secrets.DEPLOY_PORT }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
          remote_key_pass: ${{ secrets.DEPLOY_KEY_PASS }}

      - name: Restart bot via ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          port: ${{ secrets.DEPLOY_PORT }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          passphrase: ${{ secrets.DEPLOY_KEY_PASS }}
          script: sudo systemctl restart tg_twitter_bot_dev.service

